app:
    env:  "production"
    port: ":3006"
    debug: false

mongodb:
    connection: "mongodb://188.166.219.22:27017"
    db: "Runex"
    user: "idever"
    pass: "idever@987"
    
redis:
    host: "188.166.219.22"
    port: "6379"
    pass: "__@redis__P@ss"

log:
    level: "debug"
    format: "json"

omise:
    OmisePublicKey: "pkey_5i1p3nkjgq6vrrrfhkp"
    OmiseSecretKey: "skey_5i6wunbg5thk3eqd5kk"

swagger:
    base_api: "https://api.runex.co"
    base_path: "/api/v2"