app:
    env:  "development"
    port: ":3006"
    debug: true

mongodb:
    connection: "mongodb://128.199.163.81:27017"
    db: "Runex"
    user: "idever"
    pass: "idever@987"
redis:
    host: "128.199.163.81"
    port: "6379"
    pass: "__@redis__P@ss"

log:
    level: "debug"
    format: "json"

events:
    api: "https://events-api.thinkdev.app"

omise:
    OmisePublicKey: "pkey_test_5i6ivm4cotoab601bfr"
    OmiseSecretKey: "skey_test_5h9vov2hqe9iv55o8tu"

swagger:
    base_api: "https://runex-api.thinkdev.app"
    base_path: "/api/v2"

public:
    token: "5Dk2o03a4hPglRSUuNeEFXEah57CGQfMVjQ7f"